name: Publish release

on:
  push:
    branches: ["main"]
    
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create deploy folder
      run: mkdir -p ${GITHUB_WORKSPACE}/ContinuousLightsOut
    - name: Copy HTML
      uses: canastro/copy-file-action@master
      with:
        source: "contlo.html"
        target: "ContinuousLightsOut/contlo.html"
    - name: Copy board
      uses: canastro/copy-file-action@master
      with:
        source: "board.png"
        target: "ContinuousLightsOut/board.png"
    - name: Copy click rule
      uses: canastro/copy-file-action@master
      with:
        source: "clickrule.png"
        target: "ContinuousLightsOut/clickrule.png"
    - name: Copy JS
      uses: canastro/copy-file-action@master
      with:
        source: "js"
        target: "ContinuousLightsOut/js"
        flags: "-r"
    - name: Zip release
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r ContinuousLightsOut.zip ContinuousLightsOut
    - name: Get release name
      id: release_name
      run: echo "::set-output name=relname::$(date +'Build %Y-%m-%d %H:%M:%S')"
    - name: Get tag name
      id: tag_name
      run: echo "::set-output name=tagname::$(date +'%Y-%m-%d-%H-%M-%S')"
    - name: Create release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "ContinuousLightsOut.zip"
        token: ${{secrets.GITHUB_TOKEN}}
        name: ${{steps.release_name.outputs.relname}}
        tag: ${{steps.tag_name.outputs.tagname}}
        commit: ${{github.sha}}
